### ISSUE TITLE
Should use OpenSSL::HMAC instead of Digest::HMAC in sas.rb

### ISSUE THREAD

**Issue by mcm-ham** [christian-s/azure-push#1]
https://www.omniref.com/ruby/2.0.0.preview1/symbols/Digest::HMAC
CAUTION: Use of this library is discouraged, because this implementation was meant to be experimental but somehow got into the 1.9 series without being noticed. Please use OpenSSL::HMAC in the “openssl” library instead.

digest/hmac removed in ruby 2.2.0-preview1
mailgun/mailgun-ruby#15

**Comment by mcm-ham** [comment]
digest/hmac removed in ruby 2.2.0-preview1
https://github.com/mailgun/mailgun-ruby/issues/15

**Comment by christian-s** [comment]
fixed in version 0.0.3
